### ISSUE TITLE
Scenario Development

### ISSUE THREAD

**Issue by brianWreaves** [HealthHackAu2016/BNE_urbanJungles#1]
Scenario must be identified. It should describe a very specific use case, eliminating _unknown_ factors.

It should include:
- User
- Task/Goal
- Challenges

**Comment by cnico2016** [comment]
Scenario:
User - Young man (Jason - 28 y.o.) on the autism spectrum. Identified as neurodiverse.
Task/Goal - Is planning to meet a small group of friends of coffee. He needs to navigate from the King George Square Bus Station, through to a cafe on Elizabeth Street. The meet up is happening on a Saturday at 10:30am.
Challenges - Jason has difficulty navigating through crowds, especially if his surroundings are noisy. Jason also has a movement difficulty which can sometimes make navigating through spaces with changing depths and colours challenging.
Challenges -
