### ISSUE TITLE
Rendering Engine

### ISSUE THREAD

**Issue by brianWreaves** [HealthHackAu2016/BNE_urbanJungles#9]
The development of a tool to access data and develop a journey for the user.

The data used with include:
- User sensory intensity
- Starting location
- Desired journey ending location
- Previous journey input by other app users
- Research by specialist practitioners
- Council input

**Comment by brianWreaves** [comment]
@hiremaths Is actively developing a working prototype that can be used during the presentation. The code is being stored within this GitHub.

**Comment by hiremaths** [comment]
[https://hiremaths.shinyapps.io/display/](url)

**Comment by brianWreaves** [comment]
Unknown difficulty with loading icons on a map from a data source. Furture app development is _on-hold_ until a solution is found.
